get:
  operationId: getAppVersions
  summary: List App versions
  description: Returns AppVersion list
  produces:
    - application/json
  parameters:
    - name: version_code
      in: query
      description: filter by version code
      required: false
      type: string
    - name: build_number
      in: query
      description: filter by build number
      required: false
      type: string
    - name: limit
      in: query
      description: Number of results to return per page.
      required: false
      type: integer
      default: 20
    - name: offset
      in: query
      description: The initial index from which to return the results.
      required: false
      type: integer
  responses:
    '200':
      description: successful operation
      schema:
        required:
          - count
          - results
        type: object
        properties:
          count:
            type: integer
          next:
            type: string
            format: url
            x-nullable: true
          previous:
            type: string
            format: url
            x-nullable: true
          results:
            type: array
            items:
              $ref: '#/definitions/AppVersion'
  security:
    - apiKey: []
  tags:
    - Application
parameters:
  - name: application_id
    in: path
    description: A UUID string identifying this application.
    required: true
    type: string
    format: uuid
  - name: enterprise_id
    description: A UUID string identifying enterprise.
    in: path
    required: true
    type: string