get:
  operationId: getAppVersions
  summary: List App versions
  description: Returns AppVersion list
  produces:
    - application/json
  parameters:
    - name: version_code
      in: query
      description: filter by version code
      required: false
      type: string
    - name: build_number
      in: query
      description: filter by build number
      required: false
      type: string
    - name: is_g_play
      in: query
      description: filter google play applications
      required: false
      type: boolean
    - name: approval_status
      in: query
      description: filter by approval status
      required: false
      type: string
      enum:
        - AVAILABLE
        - ACCEPTED
        - APPROVED
        - REJECTED
    - name: is_enabled
      in: query
      description: filter by enabled versions
      required: false
      type: boolean
    - name: is_default
      in: query
      description: filter by default versions
      required: false
      type: boolean
    - name: created_on_gt
      in: query
      description: filter applications created after a given timestamp
      required: false
      type: string
      format: datetime
    - name: created_on_lt
      in: query
      description: filter applications created before a given timestamp
      required: false
      type: string
      format: datetime
    - name: updated_on_gt
      in: query
      description: filter applications updated after a given timestamp
      required: false
      type: string
      format: datetime
    - name: updated_on_lt
      in: query
      description: filter applications updated before a given timestamp
      required: false
      type: string
      format: datetime
    - name: limit
      in: query
      description: Number of results to return per page.
      required: false
      type: integer
      default: 20
    - name: offset
      in: query
      description: The initial index from which to return the results.
      required: false
      type: integer
      default: 0
    - name: ordering
      in: query
      description: |
        Order result set by field name.

        ```
        * installed_count: order by asc
        * -installed_count: order by desc
        ```
      required: false
      type: string
  responses:
    '200':
      description: successful operation
      schema:
        required:
          - count
          - results
        type: object
        properties:
          count:
            type: integer
          next:
            type: string
            format: url
            x-nullable: true
          previous:
            type: string
            format: url
            x-nullable: true
          results:
            type: array
            items:
              $ref: '#/definitions/AppVersion'
    '401':
      description: Authorization information is missing or invalid.
      schema: 
        $ref: '#/definitions/ErrorResponse'
    '500':
      description: Internal server error
      schema: 
        $ref: '#/definitions/ErrorResponse'
  security:
    - apiKey: []
  tags:
    - Application
parameters:
  - name: application_id
    in: path
    description: A UUID string identifying this application.
    required: true
    type: string
    format: uuid
  - name: enterprise_id
    description: A UUID string identifying enterprise.
    in: path
    required: true
    type: string