get:
  operationId: getAllApplicationsV1
  summary: List apps in enterprise
  description: Returns Application list
  produces:
    - application/json
  parameters:
    - name: application_name
      in: query
      description: filter by application name
      required: false
      type: string
    - name: package_name
      in: query
      description: filter by package name
      required: false
      type: string
    - name: package_name_exact
      in: query
      description: filter by package name (exact match)
      required: false
      type: boolean
    - name: has_uploaded_version
      in: query
      description: Returns applications having atleast on version uploaded
      required: false
      type: boolean
    - name: category
      in: query
      description: filter by category
      required: false
      type: string
    - name: supported_sdk
      in: query
      description: filter by supported sdk versions
      required: false
      type: integer
    - name: is_active
      in: query
      description: filter by active applications
      required: false
      type: boolean
    - name: is_hidden
      in: query
      description: filter default esper apps
      required: false
      type: boolean
      default: false
    - name: created_on_gt
      in: query
      description: filter applications created after a given timestamp
      required: false
      type: string
      format: datetime
    - name: created_on_lt
      in: query
      description: filter applications created before a given timestamp
      required: false
      type: string
      format: datetime
    - name: updated_on_gt
      in: query
      description: filter applications updated after a given timestamp
      required: false
      type: string
      format: datetime
    - name: updated_on_lt
      in: query
      description: filter applications updated before a given timestamp
      required: false
      type: string
      format: datetime
    - name: limit
      in: query
      description: Number of results to return per page.
      required: false
      type: integer
      default: 20
    - name: offset
      in: query
      description: The initial index from which to return the results.
      required: false
      type: integer
      default: 0
  responses:
    '200':
      description: successful operation
      schema:
        required:
          - count
          - results
        type: object
        properties:
          count:
            type: integer
          next:
            type: string
            format: url
            x-nullable: true
          previous:
            type: string
            format: url
            x-nullable: true
          results:
            type: array
            items:
              $ref: '#/definitions/ApplicationV1'
    '401':
      description: Authorization information is missing or invalid.
      schema: 
        $ref: '#/definitions/ErrorResponse'
    '500':
      description: Internal server error
      schema: 
        $ref: '#/definitions/ErrorResponse'
  security:
    - apiKey: []
  tags:
    - Application V1
parameters:
  - name: enterprise_id
    description: A UUID string identifying this enterprise.
    in: path
    required: true
    type: string